version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: adam
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: adam
      ME_CONFIG_MONGODB_ADMINPASSWORD: mysecretpassword
      ME_CONFIG_MONGODB_URL: mongodb://adam:mysecretpassword@mongo:27017/

volumes:
  mongo_data: