version: '3.8'

services:

  mongo:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - '27017:27017'
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    restart: always
    volumes:
      - mongo_data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: adam
#      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - '8081:8081'
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: adam
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mysecretpassword
#      ME_CONFIG_MONGODB_URL: mongodb://adam:mysecretpassword@mongo:27017/

volumes:
  mongo_data: